#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
i=0
while [ $i -le 24 ]
do
	if [ $i -eq 0 ]
	then
		echo "Hour: $i"
		((i++))
	fi
    j=1
	while [ $j -le 59 ]
	do
	    echo $j
	    if [ $j -eq 59 ]
	    then
	       echo "Hour: $i"
	     fi
	((j++))
	done
((i++))
done
