#!/usr/bin/env bash
# Bash script check if file exists
FILE=/home/holberton/holberton-system_engineering-devops/0x04-loops_conditions_and_parsing/holbertonschool
if [ -e "$FILE" ]
then
	echo "holbertonschool file exists"
	if [ -s "$FILE" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "holbertonschool is a regular file"
	else
		echo ""
	fi
else
	echo "holbertonschool file does not exist"
fi